apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: github
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/github"
  scopes:
    - "read:user"
  authorizationUri: "https://github.com/login/oauth/authorize"
  tokenUri: "https://github.com/login/oauth/access_token"
  userInfoUri: "https://api.github.com/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "id"
  clientName: "GitHub"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: google
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/google"
  scopes:
    - "openid"
    - "profile"
  authorizationUri: "https://accounts.google.com/o/oauth2/v2/auth"
  tokenUri: "https://oauth2.googleapis.com/token"
  userInfoUri: "https://openidconnect.googleapis.com/v1/userinfo"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "sub"
  issuerUri: "https://accounts.google.com"
  jwkSetUri: "https://www.googleapis.com/oauth2/v3/certs"
  clientName: "Google"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitee
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitee"
  scopes:
    - "user_info"
  authorizationUri: "https://gitee.com/oauth/authorize"
  tokenUri: "https://gitee.com/oauth/token"
  userInfoUri: "https://gitee.com/api/v5/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "login"
  clientName: "Gitee"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitlab
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitlab"
  scopes:
    - "read_user"
  authorizationUri: "https://gitlab.com/oauth/authorize"
  tokenUri: "https://gitlab.com/oauth/token"
  userInfoUri: "https://gitlab.com/api/v4/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "GitLab"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: linuxdo
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/linuxdo"
  scopes:
    - "openid"
    - "profile"
  authorizationUri: "https://connect.linux.do/oauth2/authorize"
  tokenUri: "https://connect.linux.do/oauth2/token"
  userInfoUri: "https://connect.linux.do/api/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "sub"
  issuerUri: "https://connect.linux.do/"
  jwkSetUri: "https://connect.linux.do/.well-known/jwks.json"
  clientName: "LINUX DO"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: sso
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/sso"
  scopes:
    - "profile"
  authorizationUri: "https://example.com/login/oauth/authorize"
  tokenUri: "https://example.com/api/login/oauth/access_token"
  userInfoUri: "https://example.com/api/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "name"
  clientName: "SSO"
