apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: github
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/github"
  scopes:
    - "read:user"
  authorizationUri: "https://github.com/login/oauth/authorize"
  tokenUri: "https://github.com/login/oauth/access_token"
  userInfoUri: "https://api.github.com/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "id"
  clientName: "GitHub"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitee
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitee"
  scopes:
    - "user_info"
  authorizationUri: "https://gitee.com/oauth/authorize"
  tokenUri: "https://gitee.com/oauth/token"
  userInfoUri: "https://gitee.com/api/v5/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "login"
  clientName: "Gitee"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitlab
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitlab"
  scopes:
    - "read_user"
  authorizationUri: "https://gitlab.com/oauth/authorize"
  tokenUri: "https://gitlab.com/oauth/token"
  userInfoUri: "https://gitlab.com/api/v4/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "GitLab"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitea
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitea"
  scopes:
    - "read:user"
    - "user:email"
  authorizationUri: "https://gitea.com/login/oauth/authorize"
  tokenUri: "https://gitea.com/login/oauth/access_token"
  userInfoUri: "https://gitea.com/login/oauth/userinfo"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "preferred_username"
  clientName: "Gitea"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: open_source_gitea
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/open_source_gitea"
  scopes:
    - "read:user"
    - "user:email"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "preferred_username"
  clientName: "Open Source Gitea"
