apiVersion: v1alpha1
kind: Setting
metadata:
  name: generic-oauth2-setting
spec:
  forms:
    - group: genericOauth
      label: "通用 OAuth 配置"
      formSchema:
        - $formkit: text
          name: clientId
          label: "Client ID"
          validation: required:trim
        - $formkit: password
          name: clientSecret
          label: "Client Secret"
          validation: required:trim
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: sso-oauth2-setting
spec:
  forms:
    - group: ssoOauth
      label: "自定义单点登录 OAuth 配置"
      formSchema:
        - $formkit: text
          name: clientId
          label: "Client ID"
          validation: required:trim
          value: "client_id"
        - $formkit: password
          name: clientSecret
          label: "Client Secret"
          validation: required:trim
          value: "client_secret"
        - $formkit: text
          name: authorizationUrl
          label: "Authorization Url"
          validation: required:trim
          value: "https://example.com/login/oauth/authorize"
        - $formkit: text
          name: tokenUrl
          label: "Token Url"
          validation: required:trim
          value: "https://example.com/api/login/oauth/access_token"
        - $formkit: text
          name: userInfoUrl
          label: "UserInfo Url"
          validation: required:trim
          value: "https://example.com/api/user"
        - $formkit: text
          name: scopes
          label: "Scopes"
          validation: required:trim
          value: "profile"
          help: "Space or comma separated list of scopes. E.g., 'openid,profile' or 'openid profile'"
        - $formkit: text
          name: userNameAttribute
          label: "UserName Attribute"
          validation: required:trim
          value: "name"
        - $formkit: text
          name: issuerUri
          label: "Issuer URI"
          help: "The Issuer Identifier of the OpenID Connect Provider."
        - $formkit: text
          name: jwkSetUri
          label: "JWK Set URI"
          help: "The URL to the JWK Set (KEYS) of the OpenID Connect Provider."
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: logto-oauth2-setting
spec:
  forms:
    - group: logtoOauth
      label: "Logto OAuth 配置"
      formSchema:
        - $formkit: text
          name: clientId
          label: "Client ID"
          validation: required:trim
        - $formkit: password
          name: clientSecret
          label: "Client Secret"
          validation: required:trim
        - $formkit: text
          name: endpoint
          label: "Endpoint"
          validation: required:trim
          value: "https://example.logto.app"
          help: "填写 Logto 域名、Issuer 或 OIDC 端点，例如 https://auth.example.com、https://auth.example.com/oidc 或 https://auth.example.com/oidc/auth。"
