apiVersion: v1alpha1
kind: Setting
metadata:
  name: generic-oauth-setting
spec:
  forms:
    - group: genericOauth
      label: "通用 OAuth 配置"
      formSchema:
        - $formkit: text
          name: clientId
          label: "Client ID"
          validation: required:trim
        - $formkit: text
          name: clientSecret
          label: "Client Secret"
          validation: required:trim
